# Generated by Django 4.2.4 on 2025-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
