# Generated by Django 5.1.7 on 2025-03-23 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_profile_address_profile_balance_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='commession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='withdrawl_amount',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_tags', models.FileField(upload_to='analysis_files/')),
                ('signi_and_rel', models.FileField(null=True, upload_to='analysis_files/')),
                ('unique_posts', models.FileField(null=True, upload_to='analysis_files/')),
                ('total_recomendation', models.FileField(null=True, upload_to='analysis_files/')),
                ('extracted_post', models.FileField(null=True, upload_to='analysis_files/')),
                ('LDA_Topic', models.FileField(null=True, upload_to='analysis_files/')),
                ('papularity_of_topics', models.FileField(null=True, upload_to='analysis_files/')),
                ('difficulty_of_topics', models.FileField(null=True, upload_to='analysis_files/')),
                ('trends_of_topics', models.FileField(null=True, upload_to='analysis_files/')),
                ('question_analysis_with_percentages', models.FileField(null=True, upload_to='analysis_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Analysis_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
