# Generated by Django 4.2.4 on 2025-04-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_plan_purchase_status'),
        ('analysis', '0016_remove_profile_balance_remove_profile_commession_and_more'),
    ]

    operations = [
    ]
