# Generated by Django 5.1.7 on 2025-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_remove_profile_balance_remove_profile_commession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='coherence_score',
            field=models.FloatField(default=0.0, max_length=30),
        ),
        migrations.AddField(
            model_name='plan_purchase',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Expired', 'Expired'), ('Active', 'Active')], default='Active', max_length=50),
        ),
    ]
