# Generated by Django 5.1.7 on 2025-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_analysis_coherence_score_plan_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='perplexity',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='coherence_score',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='plan_purchase',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
